### ISSUE TITLE
Удаление путешествия

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#103]
Если при редактировании путешествия нажать "Удалить", то ничего не произойдёт.

**Comment by evgeny-konovalov** [comment]
Реализовано.

PS: сейчас путешествие можно удалить даже если оно активно и там есть участники.
Этот usecase надо будет обсудить.

**Comment by A6bIPVALG** [comment]
Считаю нормальным, если можно удалить активное путешествие с участниками. Главное, что нужно сделать - вывести диалоговое окно, которое предупредит пользователя об активности и участниках. Даже должно быть два сообщения:
1, Это путешествие активно. Вы действительно хотите его удалить?
2. В этом путешествии заявлено <количество> Участников. Вы действительно хотите его удалить?

**Comment by A6bIPVALG** [comment]
Удалять теперь можно

**Comment by evgeny-konovalov** [comment]
Решили перед удалением выдавать одно окно с предупреждением + рассылать оповещение все участникам активного расписания.
