### ISSUE TITLE
Некорректное отображение рейтинга автора путешествия

### ISSUE THREAD

**Issue by evgeny-konovalov** [heaptrip/heaptrip#111]
В шапке путешествия в поле рейтинга автора вместо 0.25 отображается 0.259030160189587.
(см. http://beta.heaptrip.com/ct/travel_info?id=539eb0e6e4b0195198d4a4b5)

**Comment by A6bIPVALG** [comment]
там вообще не должно быть цифр. Рейтинг должен быть в звёздочках

**Comment by evgeny-konovalov** [comment]
Если будут звезды, то лента будет пестрая.
Уж лучше цифры.
А в будущем этот вопрос надо будет обсудить с дизайнером.

**Comment by dikma** [comment]
Цифра 0.259030160189587. до сих пор отображается, может ее хотя бы округлять

**Comment by A6bIPVALG** [comment]
Если должен смотреть дизайнер, то должно быть не Клозет, а какое-нибудь "светлое будущее".

**Comment by voronenko-da** [comment]
Округлил в модели до 2-х знаков RoundingMode.UP.

**Comment by A6bIPVALG** [comment]
ну, отображается 0,25 и что это мне должно говорить?

**Comment by evgeny-konovalov** [comment]
Рейтинг от 0 до 1.
0,25 - есть над чем поработать :)
Пока так. Будет дизайнер - будем причесывать. Причем причесывать будем много что, не тока рейтинг.

**Comment by A6bIPVALG** [comment]
Я перевешу это на будущее

**Comment by A6bIPVALG** [comment]
Хотя, лучше закрою
