### ISSUE TITLE
Кнопка для возврата в самый верх

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#112]
Для быстрого возврата в верхнюю часть страницы надо сделать кнопку со стрелкой, которая должна начать отображаться слева, если пользователь прокрутил страницу. Чуть ниже стрелки можно сделать картинку с квадратиками, дабы пользователь мог зайти в свой профиль, не возвращаясь в верхнюю часть страницы.

![top](https://cloud.githubusercontent.com/assets/7515433/3376247/1502102e-fbd3-11e3-84ca-6f8ec9237869.png)
рис .1. Пользователь просматривает верх страницы

![down](https://cloud.githubusercontent.com/assets/7515433/3376266/3087e49a-fbd3-11e3-9c89-924bc03ea136.png)
рис 2. Пользователь прокрутил страницу вниз. Слева появились два элемента. Их даже можно сделать полупрозрачными.

![square_select](https://cloud.githubusercontent.com/assets/7515433/3376272/51cd85ce-fbd3-11e3-8ee1-1dc9b3127105.png)
рис 3. Пользователь нажал (или навёл) курсор на квадратики. Открылось выпадающее меню. Теперь пользователь может перейти в профиль.

![guest_view](https://cloud.githubusercontent.com/assets/7515433/3376346/0d30a53a-fbd4-11e3-928b-4c15b5f6eaa1.png)
рис. 4 Вид страницы для незарегистрированного пользователя. Слева отображается стрелка для перемещения вверх и поля для логина.

**Comment by evgeny-konovalov** [comment]
Штука полезная, надо будет обсудить.
