### ISSUE TITLE
Контент, отображаемый по-умолчанию

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#114]
При входе в свой профиль я постоянно вижу надпись:

"нет записей, удовлетворяющих вашим условиям"

В категориях не выбрано ничего. Если выбрать какую-либо категорию и снять галочку, то начинает отображаться весь контент.

Если в профиле выбрать категорию и сохранить, то при следующем входе я опять не увижу записи.

**Comment by evgeny-konovalov** [comment]
Ваня, вроде пофиксили - надо проверить.

**Comment by A6bIPVALG** [comment]
Не поправлено в develop-версии

**Comment by evgeny-konovalov** [comment]
У меня отображается с первого раза.
Попробуй кэш почистить.

**Comment by A6bIPVALG** [comment]
У меня всё ещё не отображается. Кэш в браузере у меня всегда чистится при выходе. В бэте работает - закрываю до следующего прецедента.
