### ISSUE TITLE
Отображать рейтинг пользователя в диапазоне от 0 до 5-ти.

### ISSUE THREAD

**Issue by evgeny-konovalov** [heaptrip/heaptrip#40]
Сейчас от 0 до 1.

**Comment by evgeny-konovalov** [comment]
Проверил - целочисленный рейтинг плохо смотрится.
Надо будет поработать с дизайнером.
Пусть пока остается от 0 до 1.

**Comment by A6bIPVALG** [comment]
даёшь звёздочки в рейтинге! Или иные пиктограммы.
