### ISSUE TITLE
Для перемещения по истории в браузере приходится много раз нажимать одни и теже кнопки.

### ISSUE THREAD

**Issue by evgeny-konovalov** [heaptrip/heaptrip#42]
Нахожусь в профиле, перехожу на общую ленту через Супер кнопку в главменю.

Сейчас:
Нажимаю кнопку Назад -  ничего не происходит.
Чтобы перейти обратно в профиль - кнопку Назад надо нажать три раза.

Ожидется: 
Переход в профиль происходи по однократнму нажатию.

**Comment by dikma** [comment]
дубль 23
