### ISSUE TITLE
Регистрация/Логин ввод неверных данных

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#66]
При регистрации нужно проверять следующее:

Имя и фамилия не содержит специальных символов, то есть надо разрешить ввод только кириллицы и латиницы. Если введено что-нибудь другое, то выводить сообщение:"Проверьте ввод имени - используются недопустимые символы ". Вместо "имени" - "фамилии", если не то ввели в поле "Фамилия".

Имя почтового ящика может содержать только цифры, латинские буквы, точку, подчёркивание и дефис. Если введено что-то иное, то надо вывести сообщение: "Проверьте ввод адреса почты - используются недопустимые символы".

Надо проверять формат почтового ящика. То есть пользователь может ввести "имя_ящика@домен1.домен2".
Если формат не соответствует, то нужно вывести сообщение "Проверьте правильность введённой почты". При этом сообщение на почту не должно быть отправлено.

**Comment by dikma** [comment]
Валидация имени аккаунта производится, валидация email сделаю позже т.к. это нетривиальная задача
