### ISSUE TITLE
Тормозит дерево категорий

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#68]
Автоматическое обновление при выборе категории увлечений тормозит даже при одном пользователе. Может быть заменить автообновление на кнопку "Применить"?

**Comment by evgeny-konovalov** [comment]
Как сильно тормозит? У меня в браузере обновляется нормально.

**Comment by A6bIPVALG** [comment]
В Файерфоксе есть встроенная система замера времени ответа сайта. Меню -> Инструменты -> Веб-разработка -> Веб-консоль -> Сеть. Так вот, при фильтрации Ленты по значению "Познавательные туры", главная страница грузится в среднем за 0,5 - 1 секунду без нагрузки на сервер.

**Comment by voronenko-da** [comment]
Добавил серверный кэш для дерева, теперь оно для одной локали запрашивается один раз, дальше берется из кэша, и так до рестарта сервера.

**Comment by A6bIPVALG** [comment]
Ну, я разницы не увидел. Огненный Лис тоже

**Comment by voronenko-da** [comment]
Бага, не про время загрузки страницы, а про дерево категорий, а раз так, то и замерять надо запрос получения дерева категорий. 
Когда пользователь незалогинен, дерево грузится:
  Remote Address:127.0.0.1:8080
  Request URL:http://localhost:8080/heaptrip/rest/categories
  Timing:5ms
Когда залогинен:
  Timing:99 ms
Потому, что к дереву запрашивается список пользовательских категорий.

**Comment by A6bIPVALG** [comment]
согласен
