### ISSUE TITLE
Проблемы с выбором региона

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#69]
Наблюдаются искажения в отображении на странице при попытке ввести регион. Начинаю вводить "Москва" - мне выводится  "12 results are available, use up and down arrow keys to navigate.". Это сообщение перекрывает список найденных городов.
Неудобно сделан выбор найденного города - стрелками. Если уж основная навигация на сайте при помощи мыши, то всё остальное также должно управляться мышью.

Кстати, после выбора надо отображать на главной странице для какого региона отображается Лента

**Comment by evgeny-konovalov** [comment]
Тут что-то поломалось. Раньше нормально было.
