### ISSUE TITLE
Поломалось окно, предупреждающее о незарегистрированном пользователе

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#70]
![message](https://cloud.githubusercontent.com/assets/7515433/2930983/bae9a6c8-d79d-11e3-89cb-4eead9e56172.png)
Причём, чем больше нажимать на кнопку "Отправить сообщение", тем больше копий искажённого окна появится на экране.
Кстати, давайте вместо "Вы не залогинены" будем использовать "Вы не зарегистрированы"

**Comment by evgeny-konovalov** [comment]
Сообщение исправил, а вот бага не наигрывается.
