### ISSUE TITLE
Профиль. Периоды опыта и знаний

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#82]
Не сохраняетсядата "ПО". После нажатия на кнопку "Сохранить" в поле "По" устанавливается дата "С".
Опять же - долго перематывать года при установке даты.

В периодах нужно ввести понятие "Настоящее время". То есть, если человек продолжает чем-то заниматься, то зачем его ограничивать датами.

**Comment by dikma** [comment]
По поводу По разберусь, все что ниже относится к календарю, по нему есть отдельная ошибка, см. https://github.com/heaptrip/heaptrip/issues/31
