### ISSUE TITLE
Профиль. Некорректно работает сохранение Категорий и Региона

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#84]
1. Выбор региона вообще не сохраняется
2. Если нажать "Редактировать" выбрать категории, затем "Сохранить", то отмеченные галочками категории останутся на веки вечные, ка бы мы не редактировали профиль.

**Comment by evgeny-konovalov** [comment]
Проблема возникает при быстром переключении галок с последующим нажатием кнопки сохранить.

**Comment by A6bIPVALG** [comment]
Сохраняется
