### ISSUE TITLE
Error: data.begin is null. Error: data.begin is null. 

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#98]
![new bitmap image](https://cloud.githubusercontent.com/assets/7515433/3349963/5d2ea2ea-f985-11e3-9e4b-4003c4b87977.png)

В левом-верхнем углу всегда выводится сообщение об ошибке

**Comment by A6bIPVALG** [comment]
Бэта

**Comment by evgeny-konovalov** [comment]
Исправлено.

**Comment by A6bIPVALG** [comment]
ок
