### ISSUE TITLE
Невозможно создать путешествие

### ISSUE THREAD

**Issue by A6bIPVALG** [heaptrip/heaptrip#99]
Ввожу все необходимые поля, нажимаю "Сохранить", оно отвечает, что всё сохранено. Далее перехожу в раздел "Мои" и не вижу ничего.

**Comment by A6bIPVALG** [comment]
Это в Бэте

**Comment by A6bIPVALG** [comment]
Да и не в Бэте то же самое

**Comment by evgeny-konovalov** [comment]
Ваня, проверь еще раз - если что, пере откроешь багу.
У меня не наигрывается.

**Comment by A6bIPVALG** [comment]
починилось
